name: 'Build phars'
description: 'Builds phars for all systems'

runs:
  using: "composite"
  steps:
    - name: Build Castor phar for Linux
      run: bin/castor castor:phar:linux
      shell: bash

    - name: Build Castor phar for Darwin
      run: bin/castor castor:phar:darwin
      shell: bash

    - name: Build Castor phar for Windows
      run: bin/castor castor:phar:windows
      shell: bash

    - name: Ensure phar is OK
      run: build/castor.linux-amd64.phar --version
      shell: bash
      working-directory: tools/phar
